---
# tasks file for firewall_ufw
- name: allow ssh
  community.general.ufw:
      rule: limit
      port: ssh
      proto: tcp
- name: allow ssh
  community.general.ufw:
      rule: allow
      port: '80'
      proto: tcp
- name: Allow everything and enable UFW
  community.general.ufw:
    state: enabled
- name: Make sure a service is running
  systemd:
    state: started
    name: ufw
- name: Download foo.conf
  get_url:
    url: https://github.com/chaifeng/ufw-docker/raw/master/ufw-docker
    dest: /usr/local/bin/ufw-docker
    mode: '0755'
- name: ufw-docker install
  shell: 'ufw-docker install'
  become: yes