---
# tasks file for firewall_ufw
- name: allow ssh to ufw
  ufw:
    rule: limit
    port: ssh
    proto: tcp
- name: Allow all access to tcp port 80
  ufw:
    rule: allow
    port: '80'
    proto: tcp
- name: Allow everything and enable UFW
  ufw:
    state: enabled
    policy: allow
- name: Allow everything and enable UFW
  ufw:
    state: reloaded
    policy: allow