---
# tasks file for swap_on
- name: Create swap file
  command:
    dd if=/dev/zero of={{ swap_file_path }} bs=1024 count={{ swap_file_size_mb }}k
    creates="{{ swap_file_path }}"
  tags:
    - swap.file.create

- name: Change swap file permissions
  ansible.builtin.file: 
    path: "{{ swap_file_path }}"
    owner: root
    group: root
    mode: 0600
  tags:
    - swap.file.permissions

- name: "Check swap file type"
  command: file {{ swap_file_path }}
  register: swapfile
  tags:
    - swap.file.mkswap

- name: Make swap file
  command: "sudo mkswap {{ swap_file_path }}"
  when: swapfile.stdout.find('swap file') == -1
  tags:
    - swap.file.mkswap

- name: Write swap entry in fstab
  ansible.posix.mount: 
    src: '{{ swap_file_path }}'
    path: none
    fstype: swap
    opts: sw
    state: present
  tags:
    - swap.fstab

- name: Mount swap
  command: "swapon {{ swap_file_path }}"
  when: ansible_swaptotal_mb < 1
  tags:
    - swap.file.swapon