---
- name: Fetch GitHub public key
  command: ssh-keyscan -T 10 github.com
  register: keyscan
  become_user: '{{ item }}'

- name: Add GitHub public key to ssh known_hosts
  lineinfile:
    path: "{{ userhome }}/.ssh/known_hosts"
    create: yes
    line: "{{ item }}"
  with_items: '{{ keyscan.stdout_lines }}'
  become_user: '{{ item }}'