---
- name: Create user frappe
  user:
    name: "{{ user_name }}"
    password: "{{ user_password }}"
    shell: /bin/bash
    state: present
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
  become: yes
  become_method: "sudo"