---
- name: Create user frappe
  user:
    name: "{{ user_name }}"
    password: "{{ user_password }}"
    shell: /bin/bash
    state: present
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
  become: yes
  become_method: "sudo"

- name: create authorized_keys file
  ansible.builtin.file:
    path: '/home/{{ user_name }}/.ssh/authorized_keys'
    state: touch
    mode: '644'
  become_user: '{{ user_name }}'
